# Generated by Django 4.2.7 on 2023-12-09 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='absent',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 21, 14, 53, 523530)),
        ),
        migrations.AddField(
            model_name='student',
            name='big_integer_field',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='duration_field',
            field=models.DurationField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='enroll_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='file_field',
            field=models.FileField(default=None, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='student',
            name='float_field',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3),
        ),
        migrations.AddField(
            model_name='student',
            name='image_field',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='student',
            name='passed',
            field=models.BooleanField(default=None, help_text='did you pass the exam?'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(default=None, help_text='Enter address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default=None, help_text='enter your name', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
