# Generated by Django 4.2.7 on 2023-12-16 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='buyer',
            field=models.ManyToManyField(blank=True, null=True, related_name='cars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.ImageField(upload_to='cars/uploads/'),
        ),
    ]
