# Generated by Django 4.2.7 on 2023-12-17 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0002_cars_buyer_alter_cars_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='buyer',
            field=models.ManyToManyField(blank=True, related_name='cars', to=settings.AUTH_USER_MODEL),
        ),
    ]
