# Generated by Django 4.2.7 on 2023-12-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='musician',
            field=models.ManyToManyField(to='musician.musucian'),
        ),
    ]
