# Generated by Django 4.2.7 on 2023-12-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
        ('album', '0002_album_musician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='musician',
            field=models.ManyToManyField(related_name='album', to='musician.musucian'),
        ),
    ]
